package com.example.vulkaninfoapp;

public class PhysicalDeviceProperties {
    public long apiVersion;
    public long driverVersion;
    public long vendorId;
    public long deviceId;
    public int physicalDeviceType;
    public String deviceName;
    public PhysicalDeviceLimits physicalDeviceLimits;
    public PhysicalDeviceSparseProperties physicalDeviceSparseProperties;

    public static final String[] PhysicalDevicePropertyNames = {
            "API Version",
            "Driver Version",
            "Vendor ID",
            "Device ID",
            "Device Type",
            "Device Name"
    };

    public static final String[] PhysicalDeviceTypeNames = {
            "Other",
            "Integrated",
            "Discrete",
            "Virtual",
            "CPU"
    };

    public static final String[] PhysicalDeviceSparsePropertyNames = {
            "Residency standard 2D block shape",
            "Residency standard 2D multi-sample block shape",
            "Residency standard 3D block shape",
            "Residency aligned mip size",
            "Residency non-resident strict",
    };

    public static final String[] PhysicalDeviceLimitsNames = {
            "Max image dimension 1D",
            "Max image dimension 2D",
            "Max image dimension 3D",
            "Max image dimension cube",
            "Max image array layers",
            "Max texel buffer elements",
            "Max uniform buffer range",
            "Max storage buffer range",
            "Max push constants size",
            "Max memory allocation count",
            "Max sampler allocation count",
            "Buffer image granularity",
            "Sparse address space size",
            "Max bound descriptor sets",
            "Max per stage descriptor samplers",
            "Max per stage descriptor uniform buffers",
            "Max per stage descriptor storage buffers",
            "Max per stage descriptor sampled images",
            "Max per stage descriptor storage images",
            "Max per stage descriptor input attachments",
            "Max per stage resources",
            "Max descriptor set samplers",
            "Max descriptor set uniform buffers",
            "Max descriptor set uniform buffers dynamic",
            "Max descriptor set storage buffers",
            "Max descriptor set storage buffers dynamic",
            "Max descriptor set sampled images",
            "Max descriptor set storage images",
            "Max descriptor set input attachments",
            "Max vertex input attributes",
            "Max vertex input bindings",
            "Max vertex input attribute offset",
            "Max vertex input binding stride",
            "Max vertex output components",
            "Max tessellation generation level",
            "Max tessellation patch size",
            "Max tessellation control per vertex input components",
            "Max tessellation control per vertex output components",
            "Max tessellation control per patch output components",
            "Max tessellation control total output components",
            "Max tessellation evaluation input components",
            "Max tessellation evaluation output components",
            "Max geometry shader invocation",
            "Max geometry input components",
            "Max geometry output components",
            "Max geometry output vertices",
            "Max geometry total output components",
            "Max fragment input components",
            "Max fragment output attachments",
            "Max fragment dual src attachments",
            "Max fragment combined output resources",
            "Max compute shared memory size",
            "Max compute work group count",
            "Max compute work group invocations",
            "Max compute work group size",
            "Sub pixel precision bits",
            "Sub texel precision bits",
            "Mip map precision bits",
            "Max draw indexed index value",
            "Max draw indirect count",
            "Max sampler LOD bias",
            "Max sampler anisotropy",
            "Max viewports",
            "Max viewport dimensions",
            "Viewport bounds range",
            "Viewport sub pixel bits",
            "Min memory map alignment",
            "Min texel buffer offset alignment",
            "Min uniform buffer offset alignment",
            "Min storage buffer offset alignment",
            "Min texel offset",
            "Max texel offset",
            "Min texel gather offset",
            "Max texel gather offset",
            "Min interpolation offset",
            "Max interpolation offset",
            "Sub pixel interpolation offset bits",
            "Max frame buffer width",
            "Max frame buffer height",
            "Max frame buffer layers",
            "Frame buffer color sample counts",
            "Frame buffer depth sample counts",
            "Frame buffer stencil sample counts",
            "Frame buffer no attachments sample counts",
            "Max color attachments",
            "Sampled image color sample counts",
            "Sampled image integer sample counts",
            "Sampled image depth sample counts",
            "Sampled image stencil sample counts",
            "Storage image sample counts",
            "Max sample mask words",
            "Timestamp compute and graphics",
            "Timestamp period",
            "Max clip distances",
            "Max cull distances",
            "Max combined clip and cull distances",
            "Discrete queue priorities",
            "Point size range",
            "Line width range",
            "Point size granularity",
            "Line width granularity",
            "Strict lines",
            "Standard sample locations",
            "Optimal buffer copy offset alignment",
            "Optimal buffer copy row pitch alignment",
            "Non-coherent atom size"
    };
}
